import { UIContextProvider } from './context/Uisdasdsd';
import SessionProvider from './context/SessionProvider';
import { getServerSession } from 'next-auth';
import '@/css/app.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();
  
  return (
    <html lang="en">
      <body>
        <SessionProvider session={ session }>
          <UIContextProvider>
            { children }
          </UIContextProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
