import { UIContextProvider } from './context/ui';
import '@/css/app.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UIContextProvider>
          { children }
        </UIContextProvider>
      </body>
    </html>
  )
}
